import type { Character } from '../types/game';

export const INITIAL_CHARACTERS: Character[] = [
  { id: 'c1', name: 'Виктор Громов', isAlive: true, isExonerated: false },
  { id: 'c2', name: 'Марк Воронов', isAlive: true, isExonerated: false },
  { id: 'c3', name: 'Елена Соколова', isAlive: true, isExonerated: false },
  { id: 'c4', name: 'Артур Блэк', isAlive: true, isExonerated: false },
  { id: 'c5', name: 'Анна Морозова', isAlive: true, isExonerated: false },
  { id: 'c6', name: 'Дмитрий Волков', isAlive: true, isExonerated: false },
  { id: 'c7', name: 'София Романова', isAlive: true, isExonerated: false },
  { id: 'c8', name: 'Максим Лебедев', isAlive: true, isExonerated: false },
  { id: 'c9', name: 'Алиса Смирнова', isAlive: true, isExonerated: false },
  { id: 'c10', name: 'Роман Орлов', isAlive: true, isExonerated: false },
  { id: 'c11', name: 'Виктория Белова', isAlive: true, isExonerated: false },
  { id: 'c12', name: 'Игорь Новиков', isAlive: true, isExonerated: false },
  { id: 'c13', name: 'Мария Козлова', isAlive: true, isExonerated: false },
  { id: 'c14', name: 'Денис Попов', isAlive: true, isExonerated: false },
  { id: 'c15', name: 'Екатерина Ильина', isAlive: true, isExonerated: false },
  { id: 'c16', name: 'Алексей Медведев', isAlive: true, isExonerated: false },
  { id: 'c17', name: 'Дарья Кузнецова', isAlive: true, isExonerated: false },
  { id: 'c18', name: 'Павел Макаров', isAlive: true, isExonerated: false },
  { id: 'c19', name: 'Ольга Зайцева', isAlive: true, isExonerated: false },
  { id: 'c20', name: 'Сергей Степанов', isAlive: true, isExonerated: false },
  { id: 'c21', name: 'Наталья Николаева', isAlive: true, isExonerated: false },
  { id: 'c22', name: 'Андрей Семенов', isAlive: true, isExonerated: false },
  { id: 'c23', name: 'Татьяна Павлова', isAlive: true, isExonerated: false },
  { id: 'c24', name: 'Илья Богданов', isAlive: true, isExonerated: false },
  { id: 'c25', name: 'Ксения Тарасова', isAlive: true, isExonerated: false },
];
